/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/filetransfer/example/FileTransferSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createFileTransferSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< FileTransferSomeIPProxy>(_address, _connection);
}

void initializeFileTransferSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:filetransfer.example.FileTransfer:v0_1:filetransfer.example.FileTransfer",
        0x6000, 0x7000, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "filetransfer.example.FileTransfer:v0_1",
        &createFileTransferSomeIPProxy);
}

INITIALIZER(registerFileTransferSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeFileTransferSomeIPProxy);
}

FileTransferSomeIPProxy::FileTransferSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          fileChunk_(*this, 0x2000, CommonAPI::SomeIP::event_id_t(0x8020), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
{
}

FileTransferSomeIPProxy::~FileTransferSomeIPProxy() {
}


FileTransferSomeIPProxy::FileChunkEvent& FileTransferSomeIPProxy::getFileChunkEvent() {
    return fileChunk_;
}

void FileTransferSomeIPProxy::requestUpdate(uint32_t _currentVersion, CommonAPI::CallStatus &_internalCallStatus, FileTransfer::UpdateInfo &_info_, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_currentVersion(_currentVersion, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< FileTransfer::UpdateInfo, ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t> deploy_info_(static_cast< ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                FileTransfer::UpdateInfo,
                ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_currentVersion,
        _internalCallStatus,
        deploy_info_);
    _info_ = deploy_info_.getValue();
}

std::future<CommonAPI::CallStatus> FileTransferSomeIPProxy::requestUpdateAsync(const uint32_t &_currentVersion, RequestUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_currentVersion(_currentVersion, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< FileTransfer::UpdateInfo, ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t> deploy_info_(static_cast< ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                FileTransfer::UpdateInfo,
                ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_currentVersion,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< FileTransfer::UpdateInfo, ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t > _info_) {
            if (_callback)
                _callback(_internalCallStatus, _info_.getValue());
        },
        std::make_tuple(deploy_info_));
}

void FileTransferSomeIPProxy::startTransfer(std::string _fileName, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_fileName(_fileName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_accepted(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_fileName,
        _internalCallStatus,
        deploy_accepted);
    _accepted = deploy_accepted.getValue();
}

std::future<CommonAPI::CallStatus> FileTransferSomeIPProxy::startTransferAsync(const std::string &_fileName, StartTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_fileName(_fileName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_accepted(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_fileName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment > _accepted) {
            if (_callback)
                _callback(_internalCallStatus, _accepted.getValue());
        },
        std::make_tuple(deploy_accepted));
}

void FileTransferSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> FileTransferSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace example
} // namespace filetransfer
} // namespace v0
