/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_FILETRANSFER_EXAMPLE_FILE_TRANSFER_SOMEIP_STUB_ADAPTER_HPP_
#define V0_FILETRANSFER_EXAMPLE_FILE_TRANSFER_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/filetransfer/example/FileTransferStub.hpp>
#include <v0/filetransfer/example/FileTransferSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

template <typename _Stub = ::v0::filetransfer::example::FileTransferStub, typename... _Stubs>
class FileTransferSomeIPStubAdapterInternal
    : public virtual FileTransferStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> FileTransferSomeIPStubAdapterHelper;

    ~FileTransferSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        FileTransferSomeIPStubAdapterHelper::deinit();
    }

    void fireFileChunkEvent(const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_data, const bool &_lastChunk);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::filetransfer::example::FileTransferStub,
        CommonAPI::Version
    > getFileTransferInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::filetransfer::example::FileTransferStub,
        std::tuple< uint32_t>,
        std::tuple< FileTransfer::UpdateInfo>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t>
    > requestUpdateStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::filetransfer::example::FileTransferStub,
        std::tuple< std::string>,
        std::tuple< bool>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    > startTransferStubDispatcher;
    
    FileTransferSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        FileTransferSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< FileTransferStub>(_stub)),
        getFileTransferInterfaceVersionStubDispatcher(&FileTransferStub::lockInterfaceVersionAttribute, &FileTransferStub::getInterfaceVersion, false, true),
        requestUpdateStubDispatcher(
            &FileTransferStub::requestUpdate,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< ::v0::filetransfer::example::FileTransfer_::UpdateInfoDeployment_t* >(nullptr)))
        
        ,
        startTransferStubDispatcher(
            &FileTransferStub::startTransfer,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
    {
        FileTransferSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &requestUpdateStubDispatcher );
        FileTransferSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &startTransferStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2000));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8020), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFileChunkEvent(const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_data, const bool &_lastChunk) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_chunkIndex(_chunkIndex, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deployed_data(_data, static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    ,  CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment > 
    ,  bool
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8020),
            false,
             deployed_chunkIndex 
            ,  deployed_data 
            , _lastChunk
    );
}


template <typename _Stub, typename... _Stubs>
void FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::filetransfer::example::FileTransferStub, typename... _Stubs>
class FileTransferSomeIPStubAdapter
    : public FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    FileTransferSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          FileTransferSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace example
} // namespace filetransfer
} // namespace v0

#endif // V0_FILETRANSFER_EXAMPLE_File_Transfer_SOMEIP_STUB_ADAPTER_HPP_
