/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/filetransfer/example/FileTransferSomeIPStubAdapter.hpp>
#include <v0/filetransfer/example/FileTransfer.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createFileTransferSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< FileTransferSomeIPStubAdapter<::v0::filetransfer::example::FileTransferStub>>(_address, _connection, _stub);
}

void initializeFileTransferSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:filetransfer.example.FileTransfer:v0_1:filetransfer.example.FileTransfer",
         0x6000, 0x7000, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "filetransfer.example.FileTransfer:v0_1",
        &createFileTransferSomeIPStubAdapter);
}

INITIALIZER(registerFileTransferSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeFileTransferSomeIPStubAdapter);
}

} // namespace example
} // namespace filetransfer
} // namespace v0
