/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_FILETRANSFER_EXAMPLE_FILE_TRANSFER_HPP_
#define V0_FILETRANSFER_EXAMPLE_FILE_TRANSFER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

class FileTransfer {
public:
    virtual ~FileTransfer() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    struct UpdateInfo : CommonAPI::Struct< bool, bool, uint32_t, uint64_t, uint32_t, int32_t> {
    
        UpdateInfo()
        {
            std::get< 0>(values_) = false;
            std::get< 1>(values_) = false;
            std::get< 2>(values_) = 0ul;
            std::get< 3>(values_) = 0ull;
            std::get< 4>(values_) = 0ul;
            std::get< 5>(values_) = 0;
        }
        UpdateInfo(const bool &_exists, const bool &_isNew, const uint32_t &_newVersion, const uint64_t &_size, const uint32_t &_crc, const int32_t &_resultCode)
        {
            std::get< 0>(values_) = _exists;
            std::get< 1>(values_) = _isNew;
            std::get< 2>(values_) = _newVersion;
            std::get< 3>(values_) = _size;
            std::get< 4>(values_) = _crc;
            std::get< 5>(values_) = _resultCode;
        }
        inline const bool &getExists() const { return std::get< 0>(values_); }
        inline void setExists(const bool _value) { std::get< 0>(values_) = _value; }
        inline const bool &getIsNew() const { return std::get< 1>(values_); }
        inline void setIsNew(const bool _value) { std::get< 1>(values_) = _value; }
        inline const uint32_t &getNewVersion() const { return std::get< 2>(values_); }
        inline void setNewVersion(const uint32_t &_value) { std::get< 2>(values_) = _value; }
        inline const uint64_t &getSize() const { return std::get< 3>(values_); }
        inline void setSize(const uint64_t &_value) { std::get< 3>(values_) = _value; }
        inline const uint32_t &getCrc() const { return std::get< 4>(values_); }
        inline void setCrc(const uint32_t &_value) { std::get< 4>(values_) = _value; }
        inline const int32_t &getResultCode() const { return std::get< 5>(values_); }
        inline void setResultCode(const int32_t &_value) { std::get< 5>(values_) = _value; }
        inline bool operator==(const UpdateInfo& _other) const {
        return (getExists() == _other.getExists() && getIsNew() == _other.getIsNew() && getNewVersion() == _other.getNewVersion() && getSize() == _other.getSize() && getCrc() == _other.getCrc() && getResultCode() == _other.getResultCode());
        }
        inline bool operator!=(const UpdateInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
};

const char* FileTransfer::getInterface() {
    return ("filetransfer.example.FileTransfer:v0_1");
}

CommonAPI::Version FileTransfer::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace example
} // namespace filetransfer
} // namespace v0

namespace CommonAPI {
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_FILETRANSFER_EXAMPLE_FILE_TRANSFER_HPP_
