/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_DEFAULT_HPP_
#define V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/filetransfer/example/FileTransferStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace filetransfer {
namespace example {

/**
 * Provides a default implementation for FileTransferStubRemoteEvent and
 * FileTransferStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT FileTransferStubDefault
    : public virtual FileTransferStub {
public:
    COMMONAPI_EXPORT FileTransferStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(FileTransfer::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT FileTransferStubRemoteEvent* initStubAdapter(const std::shared_ptr< FileTransferStubAdapter> &_adapter) {
        CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void requestUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _currentVersion, requestUpdateReply_t _reply) {
        (void)_client;
        (void)_currentVersion;
        FileTransfer::UpdateInfo info_ = {};
        _reply(info_);
    }
    COMMONAPI_EXPORT virtual void startTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _fileName, startTransferReply_t _reply) {
        (void)_client;
        (void)_fileName;
        bool accepted = false;
        _reply(accepted);
    }
    COMMONAPI_EXPORT virtual void fireFileChunkEvent(const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_data, const bool &_lastChunk) {
        FileTransferStub::fireFileChunkEvent(_chunkIndex, _data, _lastChunk);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual FileTransferStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(FileTransferStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        FileTransferStubDefault *defaultStub_;
    };
protected:
    FileTransferStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace example
} // namespace filetransfer
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_DEFAULT
