/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_HPP_
#define V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_HPP_

#include <v0/filetransfer/example/FileTransferProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

template <typename ... _AttributeExtensions>
class FileTransferProxy
    : virtual public FileTransfer,
      virtual public FileTransferProxyBase,
      virtual public _AttributeExtensions... {
public:
    FileTransferProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~FileTransferProxy();

    typedef ::v0::filetransfer::example::FileTransfer InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls requestUpdate with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void requestUpdate(uint32_t _currentVersion, CommonAPI::CallStatus &_internalCallStatus, FileTransfer::UpdateInfo &_info_, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls requestUpdate with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> requestUpdateAsync(const uint32_t &_currentVersion, RequestUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls startTransfer with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void startTransfer(std::string _fileName, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls startTransfer with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> startTransferAsync(const std::string &_fileName, StartTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast fileChunk.
     */
    virtual FileChunkEvent& getFileChunkEvent() {
        return delegate_->getFileChunkEvent();
    }



 private:
    std::shared_ptr< FileTransferProxyBase> delegate_;
};

typedef FileTransferProxy<> FileTransferProxyDefault;


//
// FileTransferProxy Implementation
//
template <typename ... _AttributeExtensions>
FileTransferProxy<_AttributeExtensions...>::FileTransferProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< FileTransferProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< FileTransferProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
FileTransferProxy<_AttributeExtensions...>::~FileTransferProxy() {
}

template <typename ... _AttributeExtensions>
void FileTransferProxy<_AttributeExtensions...>::requestUpdate(uint32_t _currentVersion, CommonAPI::CallStatus &_internalCallStatus, FileTransfer::UpdateInfo &_info_, const CommonAPI::CallInfo *_info) {
    delegate_->requestUpdate(_currentVersion, _internalCallStatus, _info_, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> FileTransferProxy<_AttributeExtensions...>::requestUpdateAsync(const uint32_t &_currentVersion, RequestUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->requestUpdateAsync(_currentVersion, _callback, _info);
}
template <typename ... _AttributeExtensions>
void FileTransferProxy<_AttributeExtensions...>::startTransfer(std::string _fileName, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, const CommonAPI::CallInfo *_info) {
    delegate_->startTransfer(_fileName, _internalCallStatus, _accepted, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> FileTransferProxy<_AttributeExtensions...>::startTransferAsync(const std::string &_fileName, StartTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->startTransferAsync(_fileName, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &FileTransferProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool FileTransferProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool FileTransferProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& FileTransferProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& FileTransferProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> FileTransferProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace example
} // namespace filetransfer
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_HPP_
