/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_HPP_
#define V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/filetransfer/example/FileTransfer.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service FileTransfer. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class FileTransferStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual FileTransfer {
 public:
    /**
    * Sends a broadcast event for fileChunk. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireFileChunkEvent(const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_data, const bool &_lastChunk) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for FileTransfer.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FileTransferStubRemoteEvent
{
public:
    virtual ~FileTransferStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service FileTransfer to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FileTransferStub
    : public virtual CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>
{
public:
    typedef std::function<void (FileTransfer::UpdateInfo _info_)> requestUpdateReply_t;
    typedef std::function<void (bool _accepted)> startTransferReply_t;

    virtual ~FileTransferStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method requestUpdate.
    virtual void requestUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _currentVersion, requestUpdateReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method startTransfer.
    virtual void startTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _fileName, startTransferReply_t _reply) = 0;
    /// Sends a broadcast event for fileChunk.
    virtual void fireFileChunkEvent(const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_data, const bool &_lastChunk) {
        auto stubAdapter = CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireFileChunkEvent(_chunkIndex, _data, _lastChunk);
    }


    using CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<FileTransferStubAdapter, FileTransferStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef FileTransferStubRemoteEvent RemoteEventType;
    typedef ::v0::filetransfer::example::FileTransfer StubInterface;
};

} // namespace example
} // namespace filetransfer
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_FILETRANSFER_EXAMPLE_File_Transfer_STUB_HPP_
